name: Pull Request
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build and test React app
        run: |
          cd client
          npm install
          npm run build
      
